### ISSUE TITLE
1.19.2 port?

### ISSUE THREAD

**Issue by QianFuv** [wleethecoder/Thingamabobs-And-Doohickeys-Minecraft-Mod#98]
:)

**Comment by wleethecoder** [comment]
Considering it, I'll let you know if there are any updates

**Comment by QianFuv** [comment]
Thank you!

**Comment by wleethecoder** [comment]
I have found out that Minecraft version 1.19.2 uses Geckolib 3, not Geckolib 4 (the version my mod uses). Therefore, downgrading to 1.19.2 would take a lot of changes. I am not sure if I will have time to do this, but if I do, it will take a while.

**Comment by QianFuv** [comment]
Feel free to do as you wish! I'm delighted to see that this mod can be ported to 1.19.2, but I also understand if it's not possible.
